name: Elixir CI

on:
  push:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    env:
      APP_NAME: ex-tackle
      TZ: Europe/Berlin
      LANG: de_DE.UTF-8
      LC_ALL: de_DE.UTF-8
      ELIXIR_VERSION: 1.19.5
      ERLANG_VERSION: 28.5

    services:
      amqp:
        image: rabbitmq:4.2-management
        ports: ["5672:5672", "15672:15672"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}
      - name: Restore Elixir dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
            !_build/test/lib/${{ env.APP_NAME }}
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
